// packages/nepali-react/src/NepaliTextarea.tsx
import { useState, useEffect, useRef, forwardRef, useImperativeHandle, type TextareaHTMLAttributes } from 'react'
import { NepaliIMECore } from '@verishore/nepali-input'

export interface NepaliTextareaProps extends Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'onChange' | 'onInput' | 'value'> {
	value?: string
	onChange?: (value: string) => void
	onInput?: (value: string) => void
	useDevanagariDigits?: boolean
}

export interface NepaliTextareaRef {
	clear: () => void
	setValue: (value: string) => void
	getValue: () => string
	getCore: () => NepaliIMECore | null
}

export const NepaliTextarea = forwardRef<NepaliTextareaRef, NepaliTextareaProps>(
	({ value, onChange, onInput, useDevanagariDigits = true, className, ...props }, ref) => {
		const [internalValue, setInternalValue] = useState(value || '')
		const coreRef = useRef<NepaliIMECore | null>(null)
		const textareaRef = useRef<HTMLTextAreaElement>(null)

		useEffect(() => {
			coreRef.current = new NepaliIMECore({
				useDevanagariDigits,
				onStateChange: (state) => {
					setInternalValue(state.output)
					onInput?.(state.output)
					onChange?.(state.output)
				}
			})

			return () => {
				coreRef.current = null
			}
		}, [useDevanagariDigits])

		useEffect(() => {
			if (value !== undefined && value !== internalValue) {
				coreRef.current?.setValue(value)
				setInternalValue(value)
			}
		}, [value])

		useImperativeHandle(ref, () => ({
			clear: () => coreRef.current?.clear(),
			setValue: (val: string) => coreRef.current?.setValue(val),
			getValue: () => coreRef.current?.getValue() || '',
			getCore: () => coreRef.current
		}))

		const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
			if (!coreRef.current) return

			const hasSelection = textareaRef.current!.selectionStart !== textareaRef.current!.selectionEnd
			if (hasSelection && (e.key === 'Backspace' || e.key === 'Delete')) {
				e.preventDefault()
				coreRef.current.clear()
				return
			}

			const handled = coreRef.current.handleKey(e.key, {
				ctrl: e.ctrlKey,
				alt: e.altKey,
				meta: e.metaKey
			})

			if (handled) e.preventDefault()
		}

		const handlePaste = (e: React.ClipboardEvent<HTMLTextAreaElement>) => {
			if (!coreRef.current) return
			e.preventDefault()
			const text = e.clipboardData.getData('text/plain')
			coreRef.current.insertText(text)
		}

		return (
			<textarea
				{...props}
				ref={textareaRef}
				value={internalValue}
				onKeyDown={handleKeyDown}
				onPaste={handlePaste}
				onChange={(e) => {
					if (e.target.value === '') {
						coreRef.current?.clear()
					}
				}}
				className={className}
				lang="ne"
				autoComplete="off"
				autoCorrect="off"
				autoCapitalize="off"
				spellCheck={false}
			/>
		)
	}
)

NepaliTextarea.displayName = 'NepaliTextarea'

// packages/nepali-vue/src/NepaliTextarea.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch } from 'vue'
import { NepaliIMECore } from '@verishore/nepali-input'

interface Props {
  modelValue?: string
  useDevanagariDigits?: boolean
  placeholder?: string
  rows?: number
  disabled?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  modelValue: '',
  useDevanagariDigits: true,
  placeholder: '',
  rows: 4,
  disabled: false
})

const emit = defineEmits<{
  'update:modelValue': [value: string]
  'input': [value: string]
  'change': [value: string]
}>()

const textareaRef = ref<HTMLTextAreaElement | null>(null)
const internalValue = ref(props.modelValue)
let core: NepaliIMECore | null = null

onMounted(() => {
  core = new NepaliIMECore({
    useDevanagariDigits: props.useDevanagariDigits,
    onStateChange: (state) => {
      internalValue.value = state.output
      emit('update:modelValue', state.output)
      emit('input', state.output)
      emit('change', state.output)
    }
  })
})

onUnmounted(() => {
  core = null
})

watch(() => props.modelValue, (newValue) => {
  if (newValue !== internalValue.value) {
    core?.setValue(newValue)
    internalValue.value = newValue
  }
})

const handleKeyDown = (e: KeyboardEvent) => {
  if (!core) return

  const hasSelection = textareaRef.value!.selectionStart !== textareaRef.value!.selectionEnd
  if (hasSelection && (e.key === 'Backspace' || e.key === 'Delete')) {
    e.preventDefault()
    core.clear()
    return
  }

  const handled = core.handleKey(e.key, {
    ctrl: e.ctrlKey,
    alt: e.altKey,
    meta: e.metaKey
  })

  if (handled) e.preventDefault()
}

const handlePaste = (e: ClipboardEvent) => {
  if (!core) return
  e.preventDefault()
  const text = e.clipboardData?.getData('text/plain') || ''
  core.insertText(text)
}

const clear = () => core?.clear()
const setValue = (value: string) => core?.setValue(value)
const getValue = () => core?.getValue() || ''

defineExpose({
  clear,
  setValue,
  getValue,
  getCore: () => core
})
</script>

<template>
  <textarea
    ref="textareaRef"
    v-model="internalValue"
    :placeholder="placeholder"
    :rows="rows"
    :disabled="disabled"
    @keydown="handleKeyDown"
    @paste="handlePaste"
    lang="ne"
    autocomplete="off"
    autocorrect="off"
    autocapitalize="off"
    spellcheck="false"
  />
</template>
