// packages/nepali-react/src/NepaliTextarea.tsx
import { useState, useEffect, useRef, forwardRef, useImperativeHandle, type TextareaHTMLAttributes } from 'react'
import { NepaliIMECore, type DevanagariLanguage } from '@oarkflow/nepali-input'

export interface NepaliTextareaProps extends Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, 'onChange' | 'onInput' | 'value'> {
	value?: string
	onChange?: (value: string) => void
	onInput?: (value: string) => void
	useDevanagariDigits?: boolean
	language?: DevanagariLanguage
	enableExtendedRomanization?: boolean
	customWordMap?: Record<string, string>
}

export interface NepaliTextareaRef {
	clear: () => void
	setValue: (value: string) => void
	getValue: () => string
	getCore: () => NepaliIMECore | null
}

export const NepaliTextarea = forwardRef<NepaliTextareaRef, NepaliTextareaProps>(
	({ value, onChange, onInput, useDevanagariDigits = true, language = 'generic', enableExtendedRomanization = false, customWordMap, className, ...props }, ref) => {
		const [internalValue, setInternalValue] = useState(value || '')
		const coreRef = useRef<NepaliIMECore | null>(null)
		const textareaRef = useRef<HTMLTextAreaElement>(null)

		useEffect(() => {
			coreRef.current = new NepaliIMECore({
				useDevanagariDigits,
				language,
				enableExtendedRomanization,
				customWordMap,
				onStateChange: (state) => {
					setInternalValue(state.output)
					onInput?.(state.output)
					onChange?.(state.output)
				}
			})

			return () => {
				coreRef.current = null
			}
		}, [useDevanagariDigits, language, enableExtendedRomanization, customWordMap])

		useEffect(() => {
			if (value !== undefined && value !== internalValue) {
				coreRef.current?.setValue(value)
				setInternalValue(value)
			}
		}, [value])

		useImperativeHandle(ref, () => ({
			clear: () => coreRef.current?.clear(),
			setValue: (val: string) => coreRef.current?.setValue(val),
			getValue: () => coreRef.current?.getValue() || '',
			getCore: () => coreRef.current
		}))

		const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
			if (!coreRef.current) return

			const hasSelection = textareaRef.current!.selectionStart !== textareaRef.current!.selectionEnd
			if (hasSelection && (e.key === 'Backspace' || e.key === 'Delete')) {
				e.preventDefault()
				coreRef.current.clear()
				return
			}

			const handled = coreRef.current.handleKey(e.key, {
				ctrl: e.ctrlKey,
				alt: e.altKey,
				meta: e.metaKey
			})

			if (handled) e.preventDefault()
		}

		const handlePaste = (e: React.ClipboardEvent<HTMLTextAreaElement>) => {
			if (!coreRef.current) return
			e.preventDefault()
			const text = e.clipboardData.getData('text/plain')
			coreRef.current.insertText(text)
		}

		return (
			<textarea
				{...props}
				ref={textareaRef}
				value={internalValue}
				onKeyDown={handleKeyDown}
				onPaste={handlePaste}
				onChange={(e) => {
					if (e.target.value === '') {
						coreRef.current?.clear()
					}
				}}
				className={className}
				lang="ne"
				autoComplete="off"
				autoCorrect="off"
				autoCapitalize="off"
				spellCheck={false}
			/>
		)
	}
)

NepaliTextarea.displayName = 'NepaliTextarea'

// packages/nepali-solid/src/NepaliTextarea.tsx
import { createEffect, createSignal, on, onCleanup, splitProps, untrack, type JSX } from 'solid-js'
import { NepaliIMECore, type NepaliIMEState, type DevanagariLanguage } from '@oarkflow/nepali-input'
import { assignRef, callEventHandler, getKeyModifiers, mergeClassNames } from './utils'

export interface NepaliTextareaRef {
	clear: () => void
	setValue: (value: string) => void
	getValue: () => string
	getCore: () => NepaliIMECore | null
}

export interface NepaliTextareaProps extends Omit<JSX.TextareaHTMLAttributes<HTMLTextAreaElement>, 'onChange' | 'onInput' | 'value' | 'ref'> {
	value?: string
	onChange?: (value: string) => void
	onInput?: (value: string) => void
	useDevanagariDigits?: boolean
	language?: DevanagariLanguage
	enableExtendedRomanization?: boolean
	customWordMap?: Record<string, string>
	instanceRef?: (value: NepaliTextareaRef) => void
	textareaRef?: (value: HTMLTextAreaElement) => void
	className?: string
}

export function NepaliTextarea(allProps: NepaliTextareaProps) {
	const [props, rest] = splitProps(allProps, [
		'value',
		'onChange',
		'onInput',
		'useDevanagariDigits',
		'language',
		'enableExtendedRomanization',
		'customWordMap',
		'instanceRef',
		'textareaRef',
		'onKeyDown',
		'onPaste',
		'class',
		'className'
	])
	const [internalValue, setInternalValue] = createSignal(props.value ?? '')
	let core: NepaliIMECore | null = null
	let textareaElement: HTMLTextAreaElement | undefined

	const instance: NepaliTextareaRef = {
		clear: () => {
			core?.clear()
			if (!core) {
				setInternalValue('')
			}
		},
		setValue: (value: string) => {
			core?.setValue(value)
			if (!core) {
				setInternalValue(value)
			}
		},
		getValue: () => core?.getValue() ?? internalValue(),
		getCore: () => core
	}

	createEffect(() => {
		props.instanceRef?.(instance)
	})

	createEffect(() => {
		const nextCore = new NepaliIMECore({
				useDevanagariDigits: props.useDevanagariDigits ?? true,
				language: props.language ?? 'generic',
				enableExtendedRomanization: props.enableExtendedRomanization ?? false,
				customWordMap: props.customWordMap,
				onStateChange: (state: NepaliIMEState) => {
					setInternalValue(state.output)
					props.onInput?.(state.output)
					props.onChange?.(state.output)
				}
			})
		const initialValue = untrack(() => props.value ?? internalValue())

		core = nextCore
		if (initialValue) {
			nextCore.setValue(initialValue)
		}

		onCleanup(() => {
			if (core === nextCore) {
				core = null
			}
		})
	})

	createEffect(
		on(
			() => props.value,
			(externalValue) => {
				if (externalValue !== undefined && externalValue !== internalValue()) {
					core?.setValue(externalValue)
					setInternalValue(externalValue)
				}
			}
		)
	)

	const handleKeyDown: JSX.EventHandler<HTMLTextAreaElement, KeyboardEvent> = (event) => {
		callEventHandler(props.onKeyDown, event)
		if (event.defaultPrevented || !core) {
			return
		}

		const hasSelection =
			textareaElement?.selectionStart !== textareaElement?.selectionEnd

		if (hasSelection && (event.key === 'Backspace' || event.key === 'Delete')) {
			event.preventDefault()
			core.clear()
			return
		}

		const handled = core.handleKey(event.key, getKeyModifiers(event))
		if (handled) {
			event.preventDefault()
		}
	}

	const handlePaste: JSX.EventHandler<HTMLTextAreaElement, ClipboardEvent> = (event) => {
		callEventHandler(props.onPaste, event)
		if (event.defaultPrevented || !core) {
			return
		}

		event.preventDefault()
		core.insertText(event.clipboardData?.getData('text/plain') ?? '')
	}

	const handleInput: JSX.EventHandler<HTMLTextAreaElement, InputEvent> = (event) => {
		if (event.currentTarget.value === '') {
			core?.clear()
		}
	}

	return (
		<textarea
			{...rest}
			ref={(element) => {
				textareaElement = element
				assignRef(props.textareaRef, element)
			}}
			value={internalValue()}
			onKeyDown={handleKeyDown}
			onPaste={handlePaste}
			onInput={handleInput}
			class={mergeClassNames(props.class, props.className)}
			lang="ne"
			autocomplete="off"
			autocorrect="off"
			autocapitalize="off"
			spellcheck={false}
		/>
	)
}
